Add _without_check macro
rpm-software-management/rpm pull request #1256
Opened 2020-06-05 17:17 UTC by ffesti

signaling and controling whether %check is executed during build.
The macro can be set globally or in the spec file. The --nocheck
parameter of rpmbuild takes precedence, though. If --nocheck is
passed to rpmbuild the macro set accordingly. Otherwise it is set
to 0 if not defined previously.

Resolves: #316

2020-06-07 14:46 UTC, ignatenkobrain commented
I think this should set _with_check unless _without_check is defined already. Basically to have `%bcond_without check` by default without having to put it in all spec files. But still need to make sure that somebody defines `%bcond_without check`, this code won't override it.

2020-06-08 07:30 UTC, ffesti commented
May be the macro should be renamed to not collide with the with/without mechanism. The bcond mechnism assumes that the actual value is not set as a macro but only on the command line and is basically read only within the spec. If you set the macro itself having two of them can lead to the awkward situation where but are set to one or both are set to zero. So I would prefere to only have one macro.
May be _nocheck is a better name and closer resembling the cli param.

2020-06-08 10:21 UTC, torsava commented
I would like to avoid `nocheck`, because the common way to conditinalize would be `%if %{without nocheck}` and that's just confusing to read.

2020-06-08 10:24 UTC, torsava commented
> I think this should set _with_check unless _without_check is defined already. Basically to have `%bcond_without check` by default without having to put it in all spec files. But still need to make sure that somebody defines `%bcond_without check`, this code won't override it.

That would be absolutely perfect, if there's a way to do it.

2020-06-10 09:40 UTC, pmatilai commented
Yeah this needs to interact with both _with_check and _without_check, and not add semantics to %_without_check value. And for that, it'd seem that we need to parse the spec before fiddling with these values as otherwise we can't know about bcond's set in the spec.
It also needs a better commit summary regardless of implementation, this is not about some macro being added but integration between --with/without check idiom and --nocheck.

2020-08-19 07:35 UTC, pmatilai requested changes
See above.

2021-02-15 03:05 UTC, FaramosCZ commented
@ffesti Any update here?
I think this can be beneficial e.g. during the Mass Rebuilds.

2022-02-09 10:58 UTC, ffesti commented
OK, revisiting this...

Here's what happening right now without the patch:

--nocheck ->  nobuildAmount |= RPMBUILD_CHECK
--with check -> define _with_check
--without check -> define _without_check 

bcond_with(check) -> define with_check if _with_check
bcond_without(check) -> define with_check if not _without_check
  
| with_check?       | bcond_with(check) | bcond_without(check) | nothing
|----------------------- |--------------------------|-------------------------------|--------------
| nothing               |  - 	 	              | check      	            | -
| --with check       |  check                      | check	      	            | -
| --without check  |   -    	      	              | -                                   | -



> Yeah this needs to interact with both _with_check and _without_check, and not add semantics to %_without_check value. And for that, it'd seem that we need to parse the spec before fiddling with these values as otherwise we can't know about bcond's set in the spec.

I can't really see how we can parse the whole spec file first and then decide on what to do here as having a macro within the spec file is one of the objectives. I see two options:
1. Have a macro that is for --nocheck only and leave figuring out how that relates to `%with_check` to the spec author.
2. If we meddle with the --with/--without check mechanic this should work like an implicit `%bcondwithout check` line. This has the issue that it won't work properly with spec files that do have `%bcondwith check`. One way to fix this could be extending `bcond_with` and `bcond_without` to `%undefine` the `with_` macro in the `else` case. That way the defaults could be overwritten by later lines. This sounds a bit like a bad feature to advertise to packagers but may be ok for this.

Another issue here is whether any of these macros should affect whether %check is actually run. No longer running %check on a missing `%with_check` macro will change the behaviour of existing spec files. While technically not running %check should not break anything this is kinda ugly.

At the same time the `bcond` mechanic is not great to control by system wide defined macros. Yes, one could define `%_without_check` but it won't disable check done in `%bcon_with check` specs getting passed `--with check`. Otoh that may just be the desired behaviour.

2022-05-13 09:43 UTC, closed without merging

2022-12-07 12:57 UTC, sergiomb2 commented
> One way to fix this could be extending bcond_with and bcond_without to %undefine the with_ macro in the else case. That way the defaults could be overwritten by later lines. This sounds a bit like a bad feature to advertise to packagers but may be ok for this.

yeah that is other problem , 

```
%bcond_with static
%bcond_without static
%if %{with static}
echo "static is enabled on 1 "
%endif

%undefine with_static

%if %{with static}
echo "static is enabled on 2 "
%endif

```
rpmspec --parse  above first "with static" will be true but the second "with static" will not , the second is the correct 

so %bcond_without , as @ffesti  also concluded  should be %undefine the `with_` macro