Bump the Lua minimum version to 5.3.
rpm-software-management/rpm pull request #1738
Opened 2021-06-30 07:54 UTC by ppentchev

Hi,

First of all, thanks a lot for working on rpm and the related projects!

The 986be669fb037ae0e2049a2022c4fdfa05da6747 commit introduced a use of
lua_rotate(), which is not available in Lua 5.2. Hence, bump the dependency in
the configure script's pkg-config check.

Thanks in advance for your time, and keep up the great work!

G'luck,
Peter

2021-06-30 09:06 UTC, ffesti commented
Yes, something needs to be done here. I am not merging this right away, as we are pretty late in 4.17 and I am not that much into this code. Bumping required versions for something like lua requires a bit of consideration (although lua 5.3 is probably fine). As it is vacation time this may take a while, but we will definitely do something about this before the 4.17 release.

Thanks for the report (and patch)!

2021-07-02 12:19 UTC, Conan-Kudo approved these changes
I don't think it's a problem to merge this, we clearly intended to raise the Lua version accordingly when we gutted all the backwards compat code and reworked it for Lua 5.4 support.

2021-08-05 12:06 UTC, pmatilai requested changes
Introducing a dependency on 5.3 in that commit was unintentional, but then again... 5.3 is almost seven years old by now, it doesn't seem like an entirely unreasonable requirement :laughing: 

However INSTALL needs to be updated accordingly.

2021-08-06 06:52 UTC, pmatilai approved these changes

2021-08-06 06:54 UTC, merged

2021-08-06 06:54 UTC, pmatilai commented
Thanks for spotting this and the patch!