Split ___build_pre macro to make mocking rpm build environment easier
rpm-software-management/rpm pull request #2369
Opened 2023-01-26 12:15 UTC by TomasKorbar

New macro ___build_package_notes_env contains environment variables that package-notes depends on. This allows easier mocking of rpm build environment and isolated execution of check phase of rpm packages possible.

Hi,
in many tests using upstream test suite is used approach that builds sources and
tests with optflags as used in Fedora builds. This proved to be problematic since
package-notes started to depend on environment variables defined through rpm
macros. There is a workaround that can solve this but since ___build_pre macro
contains `cd` command at the end, evaluation of it in tests must be followed by
cd back to the original directory. This change allows us to get rid of this following
cd and has no effect on the current way of building.

Please see also this https://lists.fedorahosted.org/archives/list/devel@lists.fedoraproject.org/thread/UHJGLOXDDDRTHG4SC5P5FDF37OAMNRDH/ thread for more information.

Thanks for any help.

2023-01-27 21:34 UTC, Conan-Kudo commented
`package-notes` is not an upstream RPM thing, so I'm not sure what benefit it would be to have here...

2023-01-30 09:10 UTC, pmatilai requested changes
Splitting it up at some random point in the middle makes no sense for rpm.

Call it `%___build_pre_env` and move *all* the environment stuff there and I'm willing to consider.

2023-01-31 15:59 UTC, TomasKorbar commented
@pmatilai 
Done. I know that this is not an important change for rpm, but it can make peoples life
easier so i think it would be nice to merge this.

2023-02-01 06:22 UTC, pmatilai commented
Separating settings from code usually makes a whole lot of sense, even if the two have been mixed up for 25 years. There's precedent for this kind of stuff opening up worlds of new possibilities even if there's no immediate benefit to rpm itself.

Thanks for the patch!

2023-02-01 06:23 UTC, pmatilai approved these changes

2023-02-01 06:23 UTC, merged