Add RPM_LD_FLAGS to build environment
rpm-software-management/rpm pull request #2481
Opened 2023-04-12 10:14 UTC by ffesti

Based on downstream Fedora patch

2023-04-12 10:46 UTC, pmatilai commented
IIRC this hasn't been merged because it opens up the question: what about all the other related flags, should they also have their own RPM_ variables?

Actually, I wonder if this is needed at all these days, because %build_ldflags is already exported as LDFLAGS in the build scripts through %set_build_flags. Of course anything relying on RPM_LD_FLAGS would need to be updated.

2023-04-12 21:26 UTC, Conan-Kudo commented
I don't think it's unreasonable for those flags to be exposed out of the gate. It would certainly be nice if there was an extensible way to add more of them, but this patch, as it is, is simple and reasonable to mainline.

2023-04-12 21:27 UTC, Conan-Kudo requested changes

2023-04-12 21:27 UTC, Conan-Kudo commented on macros.in
> +  RPM_LD_FLAGS=\"%{?build_ldflags}\"\
I think this would be the first variable we would export which is unset by default in rpm upstream? We probably want to account for that.

2023-04-13 06:15 UTC, pmatilai commented
Well yes, but this data *already is* exported, so why would we need another variable?

This is how it originally got added to Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=728974

However, I can't find a single trace of that value ever being *used* anywhere at all! I was under the impression the redhat-hardened-* stuff in redhat-rpm-config relied on this, but even at the time of introduction, it relies on LDFLAGS instead of this variable. So it seems to me we've carried an unused downstream patch for 12 years.

But of course I could be missing some magic elsewhere. @fweimer , does anything here ring a bell, eg is RPM_LD_FLAGS relied on somewhere far away from rpm and redhat-rpm-config that wouldn't show up on my radar?

2023-04-13 06:19 UTC, pmatilai commented
Ehm, never mind that, this is widely used in Fedora specs. Sigh.

2023-04-13 06:28 UTC, pmatilai commented
...typically to set LDFLAGS, which AFAICS would've gotten the right value without this.

But the cat is out of the bag for a dozen generations of kittens and their descendants, and fighting that herd is not a hill I care to die on. So I'll submit, but @ffesti do add proper background info to the commit message so it's reasonably traceable back to the origins.

2023-06-07 16:44 UTC, kloczek commented
To be honest I have no idea why rpm source tree still cares about $RPM_*FLAGS env variables.
%configiure, %cmake and %meson are using %set_build_flags and that macro has nothing to do with $RPM_*_FLAGS.
If it something still uses $RPM_*FLAGS it is still some rare uncleaned case.

2023-06-08 09:13 UTC, pmatilai commented
@kloczek if you don't know then perhaps you should find out before making such statements.

2023-06-08 09:13 UTC, merged

2023-06-08 10:32 UTC, kloczek commented
> @kloczek if you don't know then perhaps you should find out before making such statements.

As I wrote %set_build_flags is using $CFLAGS, $CXXFLAGS, $LDFLAGS, $NM, $CC, $CXX and so on because those env variables comes with meson, GNU, autotools, cmake and even plain make.
If some project is using `$RPM_`prefixed variables it is VERY rpm specific and should be fixed.

As same adding not `$RPM_`prefixed env variable to the generated script in %__prep_{build,install} does not make to much sense (especially in case building noarch packages) because tooling macros are using %set_build_flags.

All that makes only build logs longer .. only this and nothing more.
All above logic do not depend on my knowledge (I have nothing to do with the subject).