Fix missing includes on macOS
rpm-software-management/rpm pull request #2571
Opened 2023-07-11 22:27 UTC by NattyNarwhal

These two headers were missing, and would break with implicit function declarations disabled. I assume glibc and friends includes these through other headers.

This should fix the build on macOS.

2023-07-12 10:22 UTC, Conan-Kudo approved these changes

2023-07-12 10:23 UTC, Conan-Kudo requested changes
Looks like this isn't working exactly:

From CI:

```
[ 73%] Building C object CMakeFiles/rpmuncompress.dir/tools/rpmuncompress.c.o

/srv/rpm/tools/rpmuncompress.c: In function 'doUntar':

/srv/rpm/tools/rpmuncompress.c:101:39: error: passing argument 1 of '__xpg_basename' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]

  101 |             const char *bn = basename(fn);

      |                                       ^~

In file included from /srv/rpm/tools/rpmuncompress.c:4:

/usr/include/libgen.h:34:36: note: expected 'char *' but argument is of type 'const char *'

   34 | extern char *__xpg_basename (char *__path) __THROW;

      |                              ~~~~~~^~~~~~
cc1: all warnings being treated as errors

make[3]: *** [CMakeFiles/rpmuncompress.dir/build.make:76: CMakeFiles/rpmuncompress.dir/tools/rpmuncompress.c.o] Error 1

make[2]: *** [CMakeFiles/Makefile2:703: CMakeFiles/rpmuncompress.dir/all] Error 2
```

2023-07-12 13:59 UTC, Conan-Kudo approved these changes

2023-07-26 13:12 UTC, ffesti commented
Sorry, this cast to (char*) makes me feel uneasy even if it is save here. Will merge after the test suite passes.

2023-07-26 13:21 UTC, Conan-Kudo approved these changes

2023-07-26 13:35 UTC, merged

2023-08-07 10:00 UTC, pmatilai commented
Heh, I very nearly reverted the duplicate-filename patch as bogus, there's no casting away being done in the code. Luckily I did check this conversation first :laughing: 
So the "weird" part here is why we were not seeing that const warning with glibc, but the answer is: because glibc has its own version of basename() where the argument *is* const. So yep, duping the path is the right thing to do, even if the posix basename() is dumb.