Making the os_release function more strict
rpm-software-management/rpm pull request #2657
Opened 2023-09-13 00:14 UTC by dmikushin

Making the `os_release` CMake function more strict:

1. Adding '=' to match pattern, because on Rocky Linux `/etc/os-release` contains not only `ID="rocky"`, but also `ID_LIKE="rhel centos fedora"`
2. Adding `'| xargs'`, because on Rocky Linux `ID="rocky"` line contains extra quotes

2023-09-13 07:41 UTC, dmnks commented
> Hmm, wouldn't `COMMAND sh -c ". /etc/os-release; echo ${var}"` achieve the same thing, by letting the shell do the work instead?

Yep, that's the "canonical" way to use `/etc/os-release`. For some reason, I didn't realize this when adding this cmake helper.

@dmikushin, feel free to update the PR to just source the file, otherwise I can do that later. Thanks!

2023-09-13 07:44 UTC, pmatilai commented
Heh, yeah sometimes the most obvious answer is just too obvious :smile:

2023-09-13 07:48 UTC, dmnks commented
Indeed. It makes one wonder why the file is formatted in a shell-like fashion :smile: Also, I just noticed this is also what `man os-release` illustrates in the `Example 3. Reading os-release in sh(1)` section.

2023-09-13 07:50 UTC, dmnks requested changes
Mentioned above.

2023-10-06 11:49 UTC, closed without merging

2023-10-06 11:49 UTC, pmatilai commented
Merged via #2708 since there's been no activity on this PR. Thanks for the patch + report!