Remove cycles from CMake dependency graph
rpm-software-management/rpm pull request #2820
Opened 2023-12-16 22:21 UTC by bracketttc

Attempts to generate a Ninja build from the existing CMake structure failed complaining about phony cycles related to the use of `add_custom_target` and placing the primary output file in the `DEPENDS` option.

2024-01-09 09:00 UTC, pmatilai commented on CMakeLists.txt
> +	file(GLOB man_pages docs/man/*.[1-8])
What's the reason for this? AFAICS the tarball gets updated on man page changes as it is, through the "man" target.

2024-01-09 09:07 UTC, pmatilai commented
Right, I remember encountering this pattern somewhere. Always looked like one of those cmake WTFs for me, which is probably why I tried to find some other way to do it. And as such, it was probably always for the worse.

I'll accept changing this for correctness, but note that we officially only support "make" based builds as per INSTALL.

2024-01-17 12:16 UTC, pmatilai requested changes
I came *this* close to merging, but testing made me remember why it's done the way it is: we want the tarballs always recreated on "dist". With this patch, that no longer happens.

Of course loops can't be right either, but I can't apply this as-is.

2024-01-17 13:59 UTC, pmatilai commented
Just FWIW, https://gitlab.kitware.com/cmake/cmake/-/issues/22852 describes this very case.

2024-01-18 02:43 UTC, bracketttc commented
> we want the tarballs always recreated on "dist".

Okay, I get that.

2024-02-13 07:47 UTC, pmatilai commented
Solved a bit differently by just dropping the clearly bogus BYPRODUCTS directives: #2900 

Thanks for reporting, and the patch even if it didn't get used as-is!

2024-02-13 07:47 UTC, closed without merging