Fix dependency generators sometimes dying with SIGPIPE
rpm-software-management/rpm pull request #2958
Opened 2024-03-11 11:53 UTC by pmatilai

If a dependency generator dies while we're still writing to its stdin, it causes us to die rather randomly. Typically happens with fake dependency generators that don't actually bother reading their input and/or write anything back. This is almost certainly the ghost failure we've occasionally seen in the test-suite too (#2470).

Resurrect the explicit SIG_IGN that got removed apparently in commit 375a6b5630b8e37e1d3f0c7ecbe10fe460c4d420. The matter was further confused by NSPR (which we once relied on) always setting SIGPIPE to SIG_IGN.

Suggested-by: Michael Schroeder <mls@suse.de>

Fixes: #2949

2024-03-11 12:20 UTC, ffesti commented
If the `fork()` fails the function returns without resetting the signal handler.

2024-03-11 12:56 UTC, pmatilai commented
Had this nagging feeling about the -1/0/1 returns that it actually does make a difference someplace that I'm not interested in chasing just now, so reverted that part.  It would've needed a commit message mention anyhow.

So, ignore all the rant above, this should now be rather straightforward.

2024-03-12 13:16 UTC, mlschroe requested changes
You need to set the signal handler to SIG_DFL in the child

2024-03-12 13:47 UTC, pmatilai commented
Argh, right. Not much thinking was involved in the patch creation, I admit.

2024-03-14 08:48 UTC, merged