Add --patches and --sources aliases to rpmspec
rpm-software-management/rpm pull request #3011
Opened 2024-04-02 08:19 UTC by pmatilai

These are common needs and the query is not exactly obvious, so why not.

Hijack the otherwise unused poltest.spec for the sources test, it's the only multi-source spec we have. Only, it hasn't been parseable in about ten years because of the Collections: tag, so remove that...

2024-04-02 08:58 UTC, Conan-Kudo approved these changes

2024-04-02 11:33 UTC, Conan-Kudo commented
Actually, since these emit the sources and patches in reverse order, could we make the aliases also reverse that so they are in the correct order?

2024-04-02 11:33 UTC, Conan-Kudo requested changes
Actually, since these emit the sources and patches in reverse order, could we make the aliases also reverse that so they are in the correct order?

2024-04-03 06:40 UTC, pmatilai commented
The thought crossed my mind too, I'm a bit torn on this all.

Sure, reverting the order in the aliases would be safe. But, it seems like a bug that we're storing them in reverse order in the package in the first place, and  something we should fix instead. But, that'd break it for the alleged existing users who are reverting it. Are there any? I really don't know, because few people even know you can query the patches like that.

The more I think about it, the less likely it seems that doing the right thing and reverting the order of sources and patches would break anything. Had people run into that order reversion, I would've probably heard of it. And this is actually the first time that even I so much as notice it :smile:

2024-04-03 07:05 UTC, pmatilai commented
Coming to the conclusion that it's just not worth the trouble right now. I'll revive this once we've fixed the order (filed a ticket for that)

2024-04-03 07:05 UTC, closed without merging